services:
  - type: web
    name: compassion-tracker
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false